# Generated by Django 5.1.1 on 2024-12-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobtitle", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("compname", models.TextField(blank=True, null=True)),
                ("compdesc", models.TextField(blank=True, null=True)),
                ("complocation", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
